# Generated by Django 5.2.15 on 2026-06-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog_collector_collection_feedback_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'role': 'collector'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='api.pickuprequest'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recycling', to='api.collection'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='recycled_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
