# Generated by Django 5.2.15 on 2026-06-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auditlog_details_alter_auditlog_target_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_entity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections_made', to='api.collector'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_record', to='api.pickuprequest'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recycling_record', to='api.collection'),
        ),
        migrations.AlterField(
            model_name='recycling',
            name='recycled_date',
            field=models.DateField(),
        ),
    ]
