# Generated by Django 5.2.15 on 2026-07-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auditlog_details_alter_auditlog_target_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycling',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recycling_record', to='api.collection'),
        ),
    ]
