# Generated by Django 5.2.15 on 2026-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_collection_collector_alter_collection_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='disposal_category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
    ]
